services:
    app.exception_listener:
        class: Application\Http\Listeners\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.listener.json_response_formatter:
      class: Application\Http\Listeners\JsonResponseFormatterListener
      arguments: ['@serializer']
      tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelResponse }